In [3]:
import numpy as np


In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a1 = np.array([2,4,6,2], dtype='float')

In [8]:
type(a1)

numpy.ndarray

In [9]:
a1.shape

(4,)

In [11]:
a2 = np.array([[1,2,3],[2,3,1]])
a2.shape

(2, 3)

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.ndim


2

In [14]:
a2.size

6

#Creating Numpy Arrays from Scratch

Zero, one,full, arange, linspace

In [19]:
np.zeros([2,4],dtype= 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.ones([2,4], dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [24]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###Random

In [26]:
np.random.random([4,4])

array([[0.85258586, 0.47922175, 0.12729235, 0.62826521],
       [0.41850402, 0.7081887 , 0.78652518, 0.49318325],
       [0.07799062, 0.74570306, 0.85074074, 0.35988138],
       [0.57265975, 0.4746663 , 0.59445311, 0.44721635]])

In [28]:
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [29]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [32]:
np.random.randint(0,10,[4,5])

array([[7, 2, 0, 3, 5],
       [9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8],
       [4, 3, 7, 5, 5]])

In [33]:
np.random.rand(4,4)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687],
       [0.01357164, 0.6228461 , 0.67365963, 0.971945  ],
       [0.87819347, 0.50962438, 0.05571469, 0.45115921],
       [0.01998767, 0.44171092, 0.97958673, 0.35944446]])

Indexing & Silicing

In [34]:
x1 = np.random.randint(20,size=6)

In [35]:
x1

array([ 2,  2,  3,  3, 18, 14])

In [36]:
x1[4]

18

In [38]:
x2 = np.random.randint(10,size=(3,4))

In [39]:
x2

array([[3, 4, 1, 2],
       [9, 1, 4, 6],
       [8, 2, 3, 0]])

In [40]:
x2[1,2]

4

Slicing:

In [41]:
x1[0:3]

array([2, 2, 3])

In [43]:
x1[5:6]

array([14])